### ISSUE TITLE
Donate Tahmini Ayarlamalar

### ISSUE THREAD

**Issue by ByDexterTR** [emreires/SourceMod-Donate-Plugin#2]
Bu eklenti Komutçuya atılması daha iyi olabilir.
Ses dosyaları herkes de çalsın. ( yazı , vb. şeylerde)
Sesler ve yazılar ortalama 3-4 saniye ekranda gözüken resim ve yazı 3.0 saniye olması daha iyi olabilir.
Bir oyuncu donate atarken not bırakabilsin ve not sesli okunursa güzel olur.

**Comment by emreires** [comment]
Gün içerisinde güncelleyeceğim.

**Comment by emreires** [comment]
**Halloldu 👍**
