### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ByDexterTR** [emreires/SourceMod-Donate-Plugin#3]
Normal donate atınca oluyor ( !donate emreires 50 ) yazı ve ses çalışıyor.
Fakat donate yazı yazınca olmuyor ( !donate emreires 50 test ) yazı ve ses çalışmıyor.

**Comment by emreires** [comment]
Denedin mi son halini? 5 gün önce güncelledim.

**Comment by ByDexterTR** [comment]
En son halini 1.10 compiler ile denedim fakat çalışmadı.

**Comment by emreires** [comment]
Denendi ve problem görünmüyor.
